baseurl = "http://eeeerica.github.io"
title = "Erica On The Way"
languageCode = "zh-cn"
copyright = "Copyright (c) 2008 - 2015, Erica Zhou; all rights reserved."
MetaDataFormat = "yaml"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
buildFuture=true
disqusShortname = "Erica"
theme="docdock"
[params] # for dockdock 
showVisitedLinks = true # default is false
themeVariant ="blue"

[author]
    name = "Erica Zhou"

[outputs] # for dockdock search
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/eeeerica"
weight = 10


[[menu.shortcuts]]
name = "<i class='fa fa-user'></i>  关于我"
url = "/me"
weight = 12
